#!/bin/sh
set -u

# Find include directory
if [ -n "$SNAP" ]; then
	# Run from snap
	BUILD_INCLUDE_DIR="$SNAP/include"
elif [ -z "$BUILD_INCLUDE_DIR" ]; then
	# Run from source
	BUILD_INCLUDE_DIR="$(dirname -- "$(realpath -- "$0")")/include"
	if [ ! -f "$BUILD_INCLUDE_DIR/internal/core.before"  ]; then
		# Run from classic package
		BUILD_INCLUDE_DIR=/usr/share/build/include
	fi
fi

# Find Buildfile
WHERE=.
while [ ! -f "$WHERE/Buildfile" ] && [ "$(realpath -- "$WHERE")" != / ]; do WHERE="$WHERE/.."; done
if [ ! -f "$WHERE/Buildfile" ]; then
	echo "cannot find Buildfile"
	exit 1
fi

# Run GNU make with all the right options.
MAKEFILES="$BUILD_INCLUDE_DIR/internal/core.before $WHERE/Buildfile $BUILD_INCLUDE_DIR/internal/core.after " \
	exec make \
	--jobs \
	--no-builtin-rules \
	--no-builtin-variables \
	--warn-undefined-variables \
	--include-dir="$BUILD_INCLUDE_DIR" \
	--no-print-directory \
	--output-sync=target \
	--directory="$WHERE" \
	--file /dev/null \
	"$@"
