# vim: set filetype=make :

# Build looks very carefully at all the variables and makes sure there are no
# hidden typos or unrecognized variables.
include C

PROGRAMS = hello-world
hello-world_SOURCES = hello.c

# Uncomment any of those to see more interesting diagnostic messages:
# hello-world_SRC = hello.c
# hello-werld_SOURCES = hello.c
# PREGRAMS = hello-world 
