name: build 
version: '0.1b'
summary: pure-make build system 
description: |
 Build is a simple build system that is inspired by autotools but
 has lower complexity, better defaults, saner behavior and faster
 builds.
 Build is still very experimental so please use it with caution.
architectures: [all]
grade: stable
confinement: classic
apps:
    build:
        command: build
        plugs: [home]
parts:
  build:
    source: .
    plugin: dump
    snap: [checkers, core, include, build]
